const defaultConfig = {
  radius: 600,
  autoRotate: true,
  autoRotateInSetting: true,
  moveUpward: 400,
  scaleOrigin: 190,
  startWithStacked: false,
  stackOpacity: 1,
  degreeOfLast: 10,
  videoScale: 2,
  idleVideoWidth: 640,
  greyForDoneItem: true,
  greyForDoneAll: false,
  useTitleBar: true,
  buttonFontSize: 30,
  buttonWidth: 200,
  autoPlay: false,
  seekZeroOnPlayEnd: false,
  titleType: 'fullWidth',
  titleStyle: '2',
  titleFontSize: 30,
  titleFontWeight: 500,
  titleOpacity: 1,
  animationTime: 0.5,
  rotationTime: 60,
  rotationTimeLast: 15
}
export default defaultConfig